carts/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from .import views
urlpatterns = [
    path('',views.cart,name='cart'),
]

market/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index,name='index'),
]

products/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'shop'
urlpatterns = [
    path('', views.product_list,name='product_list'),
    path('<category_slug>', views.product_list,name='product'),
    path('<id>/<slug>',views.product_detail,name='product_list_by_category'),
]

swadeshi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls')),
    path('home/', include('products.urls')),
    path('carts', include('carts.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from products.models import Product
# Create your models here.

class Cart(models.Model):
    products=models.ManyToManyField(Product,blank=True)
    total=models.DecimalField(max_digits=100,decimal_places=2,default=0.00)
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Cart Id %s" %(self.id)

market/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product', args=[self.slug])



class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True,unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)
        unique_together=('name','slug')
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.id, self.slug])
class Images(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/images/', blank=True,default='default-image.jpg')
    thumbnail=models.BooleanField(default=False)
    featured=models.BooleanField(default=False)
    available = models.BooleanField(default=True)
    updated_at = models.DateTimeField(auto_now_add=False,auto_now=True)

    def __str__(self):
        return self.product.name

carts/views.py
from django.shortcuts import render
from .models import Cart
# Create your views here.

def cart(request):
    cart=Cart.objects.all()[0]
    context={"cart":cart}
    template="cart.html"
    return render(request,template,context)


def update_cart(request,slug):
    pass

market/views.py
from django.shortcuts import render

# Create your views here.
def index(request):

    return render(request,'index.html')

products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'product/index.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    context = {
        'product': product
    }
    return render(request, 'detail.html', context)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}On-line Shop{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% include 'navbar.html' %}

{% block content %}

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

templates/cart.html
{% block content %}
{% for item in cart.products.all%}
{{item}}
{%endfor%}
{%endblock%}

templates/detail.html
{{product.name}}

templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
   <div class="container-fluid">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                  {% for product in products %}
                      <div class="col-md-4">
                        <div class="thumbnail">
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'images/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                            </a>
                            <div class="caption">
                                <h3 class="text-center">
                                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                </h3>
                                <p class="text-center">Kshs. {{ product.price }}</p>
                            </div>
                        </div>
                      </div>
                  {% endfor %}
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module">
            <h4>Categories</h4>
            <ol class="list-unstyled">
              <li {% if not category %} class="active"{% endif %}><a href="{% url 'shop:product_list' %}">All</a></li>
            {% for c in categories %}

              <li {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}

templates/market/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Swadeshi</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/myjs.js' %}" type="text/javascript"></script>
</head>
  <body>
    <!-- here we are going to define navbar -->
    {% include 'market/navbar.html'%}

    <!-- here include side menus -->
    {% include 'market/sidebar.html'%}
    {%block content%}

    {%endblock%}
<!-- here including website features -->
{% include 'market/website_features.html'%}
    <!-- here including footer  -->
{% include 'market/footer.html'%}

  </body>
</html>

templates/market/footer.html
{% load static %}
<!------------Footer----------->
<section class="footer">
<div class="container tex-center">
    <div class="row">
        <div class="col-md-3">
            <h1>Useful Links</h1>
            <p>Privacy Policy</p>
            <p>Terms of Use</p>
            <p>Return Policy</p>
            <p>Discount Coupons</p>
        </div>

        <div class="col-md-3">
            <h1>Company</h1>
            <p>About Us</p>
            <p>Contact Us</p>
            <p>Career</p>
            <p>Affiliate</p>
        </div>
        <div class="col-md-3">
            <h1>Follow Us On</h1>
            <p><i class="fa fa-facebook-official"></i> Facebook</p>
            <p><i class="fa fa-youtube-play"></i> YouTube</p>
            <p><i class="fa fa-linkedin"></i> Linkedin</p>
            <p><i class="fa fa-twitter"></i> Twitter</p>
        </div>
        <div class="col-md-3 footer-image">
            <h1>Download App</h1>
            <img src="{% static 'images/app-logo.png' %}">
        </div>
    </div>
    <hr>
    <p class="copyright">Made with <i class="fa fa-heart-o"></i> by Easy Tutorials</p>
</div>
</section>

templates/market/navbar.html
{% load static %}
<div class="top-nav-bar">
<div class="search-box">
    <i class="fa fa-bars" id="menu-btn" onclick="openmenu()"></i>
    <i class="fa fa-times" id="close-btn" onclick="closemenu()"></i>

<img src="{% static 'images/orange-logo.png' %}" class="logo">
<input type="text" class="form-control">
<span class="input-group-text"><i class="fa fa-search"></i></span>
</div>
<div class="menu-bar">
<ul>
<li><a href="#"><i class="fa fa-shopping-basket"></i>cart</a></li>
<li><a href="#">Sign Up</a></li>
<li><a href="#">Log In</a></li>
</ul>
</div>
</div>

templates/market/sidebar.html
{% load static %}
<section class="header">
<div class="side-menu" id="side-menu">
<ul>
        <li>On sale <i class="fa fa-angle-right"></i>
            <ul>
            <li>Sub Menu-1</li>
            <li>Sub Menu-1</li>
            <li>Sub Menu-1</li>
            <li>Sub Menu-1</li>
            </ul>
        </li>

        <li>Mobiles<i class="fa fa-angle-right"></i>
        <ul>
            <li>Sub Menu-2</li>
            <li>Sub Menu-2</li>
            <li>Sub Menu-2</li>
            <li>Sub Menu-2</li>
            </ul>
        </li>

        <li>Computers <i class="fa fa-angle-right"></i>
            <ul>
            <li>Sub Menu-3</li>
            <li>Sub Menu-3</li>
            <li>Sub Menu-3</li>
            <li>Sub Menu-3</li>
            </ul>
        </li>

        <li>Books <i class="fa fa-angle-right"></i>
            <ul>
            <li>Sub Menu-4</li>
            <li>Sub Menu-4</li>
            <li>Sub Menu-4</li>
            <li>Sub Menu-4</li>
            </ul>
        </li>

        <li>Fitness <i class="fa fa-angle-right"></i>
            <ul>
            <li>Sub Menu-5</li>
            <li>Sub Menu-5</li>
            <li>Sub Menu-5</li>
            <li>Sub Menu-5</li>
            </ul>
        </li>

        <li>Beby Care <i class="fa fa-angle-right"></i>
            <ul>
            <li>Sub Menu-6</li>
            <li>Sub Menu-6</li>
            <li>Sub Menu-6</li>
            <li>Sub Menu-6</li>
            </ul>
        </li>

        <li>Magazines <i class="fa fa-angle-right"></i>
            <ul>
            <li>Sub Menu-7</li>
            <li>Sub Menu-7</li>
            <li>Sub Menu-7</li>
            <li>Sub Menu-7</li>
            </ul>
        </li>

        <li>Auto Accessories <i class="fa fa-angle-right"></i>
            <ul>
            <li>Sub Menu-8</li>
            <li>Sub Menu-8</li>
            <li>Sub Menu-8</li>
            <li>Sub Menu-8</li>
            </ul>
        </li>

        <li>Movies and Music <i class="fa fa-angle-right"></i>
            <ul>
            <li>Sub Menu-9</li>
            <li>Sub Menu-9</li>
            <li>Sub Menu-9</li>
            <li>Sub Menu-9</li>
            </ul>
        </li>

        <li>Video and Games <i class="fa fa-angle-right"></i>
            <ul>
            <li>Sub Menu-10</li>
            <li>Sub Menu-10</li>
            <li>Sub Menu-10</li>
            <li>Sub Menu-10</li>
            </ul>
        </li>

        <li>Home and Kitchen <i class="fa fa-angle-right"></i>
            <ul>
            <li>Sub Menu-11</li>
            <li>Sub Menu-11</li>
            <li>Sub Menu-11</li>
            <li>Sub Menu-11</li>
            </ul>
        </li>

        <li>Furniture <i class="fa fa-angle-right"></i>
            <ul>
            <li>Sub Menu-12</li>
            <li>Sub Menu-12</li>
            <li>Sub Menu-12</li>
            <li>Sub Menu-12</li>
            </ul>
        </li>

        <li>Grocery <i class="fa fa-angle-right"></i>
            <ul>
            <li>Sub Menu-13</li>
            <li>Sub Menu-13</li>
            <li>Sub Menu-13</li>
            <li>Sub Menu-13</li>
            </ul>
        </li>
    </ul>
</div>
<div class="slider">
  <div id="slider" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/img-1.jpeg' %}" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/img-2.jpeg' %}" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/img-3.jpeg' %}" class="d-block w-100">
    </div>
      <div class="carousel-item">
      <img src="{% static 'images/img-4.jpeg' %}" class="d-block w-100">
    </div>
  </div>
  <ol class="carousel-indicators">
    <li data-target="#slider" data-slide-to="0" class="active"></li>
    <li data-target="#slider" data-slide-to="1"></li>
    <li data-target="#slider" data-slide-to="2"></li>
    <li data-target="#slider" data-slide-to="3"></li>
  </ol>
</div>
</div>

</section>

templates/market/website_features.html
<!----------------Website features----------------->
{% load static %}
<section class="website-features">
<div class="container">
<div class="row">
<div class="col-md-3 feature-box">
<img src="{% static 'images/feature-1.png' %}">
<div class="feature-text">
<p><b>100% Original items </b>are available at company</p>
</div>
</div>
<div class="col-md-3 feature-box">
<img src="{% static 'images/feature-2.png' %}">
<div class="feature-text">
<p><b>Return within 30 days </b>of receiving your order.</p>
</div>
</div>
<div class="col-md-3 feature-box">
<img src="{% static 'images/feature-3.png' %}">
<div class="feature-text">
<p><b>Get free delivery for every</b>order on more than price.</p>
</div>
</div>
<div class="col-md-3 feature-box">
<img src="{% static 'images/feature-4.png' %}">
<div class="feature-text">
<p><b>Pay Online through multiple </b>options (card/Net banking)</p>
</div>
</div>
</div>
</div>
</section>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0px; background-color: #5AC8FA;">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container-fluid">
      <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'shop:product_list' %}" style="color: #ffffff">Henrylab Network</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
          {% if request.user.is_authenticated %}
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">{{ request.user.username }}<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="">logout</a></li>
            {% else %}
          <li class="divider"></li>
          <li><a href="#" style="color: #ffffff">Sign in</a></li>
         <li><a href="#" style="color: #ffffff">Sign up</a></li>
        </ul>
         {% endif %}
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>

templates/product/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Swadeshi</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/myjs.js' %}" type="text/javascript"></script>
</head>
  <body>
    <!-- here we are going to define navbar -->
    {% include 'product/navbar.html'%}

    <!-- here include side menus -->
    {% include 'product/sidebar.html'%}
    {%block content%}

    {%endblock%}
<!-- here including website features -->
{% include 'product/website_features.html'%}
    <!-- here including footer  -->
{% include 'product/footer.html'%}

  </body>
</html>

templates/product/footer.html
{% load static %}
<!------------Footer----------->
<section class="footer">
<div class="container tex-center">
    <div class="row">
        <div class="col-md-3">
            <h1>Useful Links</h1>
            <p>Privacy Policy</p>
            <p>Terms of Use</p>
            <p>Return Policy</p>
            <p>Discount Coupons</p>
        </div>

        <div class="col-md-3">
            <h1>Company</h1>
            <p>About Us</p>
            <p>Contact Us</p>
            <p>Career</p>
            <p>Affiliate</p>
        </div>
        <div class="col-md-3">
            <h1>Follow Us On</h1>
            <p><i class="fa fa-facebook-official"></i> Facebook</p>
            <p><i class="fa fa-youtube-play"></i> YouTube</p>
            <p><i class="fa fa-linkedin"></i> Linkedin</p>
            <p><i class="fa fa-twitter"></i> Twitter</p>
        </div>
        <div class="col-md-3 footer-image">
            <h1>Download App</h1>
            <img src="{% static 'images/app-logo.png' %}">
        </div>
    </div>
    <hr>
    <p class="copyright">Bharat <i class="fa fa-heart-o"> Swadeshi</i> </p>
</div>
</section>

templates/product/index.html
{% extends 'product/base.html' %}
{% block content %}
{% load static%}

<section class="featured-categories">

<div class="container">
 <div class="row">
     <div class="col-md-4">
     <img src="{% static 'images/categories1.jpg' %}">
    </div>
     <div class="col-md-4">
     <img src="{% static 'images/categories2.jpeg' %}">
    </div>
     <div class="col-md-4">
     <img src="{% static 'images/categories3.jpeg' %}">
    </div>
</div>
</div>

</section>


<!-----------------On Sale product------------------>
<section class="on-sale">
<div class="container">
    <div class="title-box">
    <h2>On Sale</h2>
    </div>
    <div class="row">
{% for product in products%}
    <div class="col-md-3">

    <div class="product-top">
      <a href='{{product.get_absolute_url}}'>
      {%if product.images_set.all%}
      {% for item in product.images_set.all%}
     <img src="{{MEDIA_URL}}{{item.image}}"   alt="Image" height="270" width="170">
     {%endfor%}
     {%else%}
     <img src="{% static 'coffeecup_gilitzer-758979.jpg' %}">
     {%endif%}




        <div class="overlay-right">

        <button type="button" class="btn btn-secondary" title="Quick Shop">
           <i class="fa fa-eye"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to Wishlist">
           <i class="fa fa-heart-o"></i>
        </button>
            <button type="button" class="btn btn-secondary" title="Add to Cart">
           <i class="fa fa-shopping-cart"></i>
        </button>
        </div>
    </div>


    <div class="product-bottom text-center">

      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star-half-o"></i>
      <h4>{{product.name}}</h4>
      <h5>{{product.price}}</h5>

    </div>

    </div>

{%endfor%}
    </div>
</div>
</section>

<!--------------New Products----------------->
<section class="new-products">
   <div class="container">
    <div class="title-box">
    <h2>New Arrivals</h2>
    </div>
    <div class="row">
    <div class="col-md-3">
    <div class="product-top">
        <a href="#"><img src="{% static 'images/product1.jpg' %}"></a>
        <div class="overlay-right">
        <button type="button" class="btn btn-secondary" title="Quick Shop">
           <i class="fa fa-eye"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to Wishlist">
           <i class="fa fa-heart-o"></i>
        </button>
            <button type="button" class="btn btn-secondary" title="Add to Cart">
           <i class="fa fa-shopping-cart"></i>
        </button>
        </div>
    </div>
    <div class="product-bottom text-center">
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star-half-o"></i>
        <h3>Fitness Watch</h3>
        <h5>$40.00</h5>
    </div>
    </div>

    <div class="col-md-3">
    <div class="product-top">
        <a href="#"><img src="{% static 'images/product2.jpg' %}"></a>
        <div class="overlay-right">
        <button type="button" class="btn btn-secondary" title="Quick Shop">
           <i class="fa fa-eye"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to Wishlist">
           <i class="fa fa-heart-o"></i>
        </button>
            <button type="button" class="btn btn-secondary" title="Add to Cart">
           <i class="fa fa-shopping-cart"></i>
        </button>
        </div>
    </div>
    <div class="product-bottom text-center">
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
        <h3>Smart Watch</h3>
        <h5>$50.00</h5>
    </div>
    </div>

    <div class="col-md-3">
    <div class="product-top">
        <a href="#"><img src="{% static 'images/product3.jpg' %}"></a>
        <div class="overlay-right">
        <button type="button" class="btn btn-secondary" title="Quick Shop">
           <i class="fa fa-eye"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to Wishlist">
           <i class="fa fa-heart-o"></i>
        </button>
            <button type="button" class="btn btn-secondary" title="Add to Cart">
           <i class="fa fa-shopping-cart"></i>
        </button>
        </div>
    </div>
    <div class="product-bottom text-center">
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
        <h3>Formarl Shoes</h3>
        <h5>$500.00</h5>
    </div>
    </div>

    <div class="col-md-3">
    <div class="product-top">
        <a href="#"><img src="{% static 'images/product4.jpg' %}"></a>
        <div class="overlay-right">
        <button type="button" class="btn btn-secondary" title="Quick Shop">
           <i class="fa fa-eye"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to Wishlist">
           <i class="fa fa-heart-o"></i>
        </button>
            <button type="button" class="btn btn-secondary" title="Add to Cart">
           <i class="fa fa-shopping-cart"></i>
        </button>
        </div>
    </div>
    <div class="product-bottom text-center">
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star-half-o"></i>
      <i class="fa fa-star-o"></i>
        <h3>Leather Watch</h3>
        <h5>$300.00</h5>
    </div>
    </div>

    <div class="col-md-3">
    <div class="product-top">
        <a href="#"><img src="{% static 'images/product1.jpg' %}"></a>
        <div class="overlay-right">
        <button type="button" class="btn btn-secondary" title="Quick Shop">
           <i class="fa fa-eye"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to Wishlist">
           <i class="fa fa-heart-o"></i>
        </button>
            <button type="button" class="btn btn-secondary" title="Add to Cart">
           <i class="fa fa-shopping-cart"></i>
        </button>
        </div>
    </div>
    <div class="product-bottom text-center">
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star-half-o"></i>
        <h3>Fitness Watch</h3>
        <h5>$40.00</h5>
    </div>
    </div>

    <div class="col-md-3">
    <div class="product-top">
        <a href="#"><img src="{% static 'images/product2.jpg' %}"></a>
        <div class="overlay-right">
        <button type="button" class="btn btn-secondary" title="Quick Shop">
           <i class="fa fa-eye"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to Wishlist">
           <i class="fa fa-heart-o"></i>
        </button>
            <button type="button" class="btn btn-secondary" title="Add to Cart">
           <i class="fa fa-shopping-cart"></i>
        </button>
        </div>
    </div>
    <div class="product-bottom text-center">
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
        <h3>Smart Watch</h3>
        <h5>$50.00</h5>
    </div>
    </div>

    <div class="col-md-3">
    <div class="product-top">
        <a href="#"><img src="{% static 'images/product3.jpg' %}"></a>
        <div class="overlay-right">
        <button type="button" class="btn btn-secondary" title="Quick Shop">
           <i class="fa fa-eye"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to Wishlist">
           <i class="fa fa-heart-o"></i>
        </button>
            <button type="button" class="btn btn-secondary" title="Add to Cart">
           <i class="fa fa-shopping-cart"></i>
        </button>
        </div>
    </div>
    <div class="product-bottom text-center">
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
        <h3>Formarl Shoes</h3>
        <h5>$500.00</h5>
    </div>
    </div>

    <div class="col-md-3">
    <div class="product-top">
        <a href="#"><img src="{% static 'images/product4.jpg' %}"></a>
        <div class="overlay-right">
        <button type="button" class="btn btn-secondary" title="Quick Shop">
           <i class="fa fa-eye"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to Wishlist">
           <i class="fa fa-heart-o"></i>
        </button>
            <button type="button" class="btn btn-secondary" title="Add to Cart">
           <i class="fa fa-shopping-cart"></i>
        </button>
        </div>
    </div>
    <div class="product-bottom text-center">
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star"></i>
      <i class="fa fa-star-half-o"></i>
      <i class="fa fa-star-o"></i>
        <h3>Leather Watch</h3>
        <h5>$300.00</h5>
    </div>
    </div>

    </div>
</div>
</section>

{% endblock %}